### ISSUE TITLE
Better understanding

### ISSUE THREAD

**Issue by xyzzy529** [ags131/screeps-console-helper#1]
I have installed the script.

The Tampermonkey editor showed several lines where ending ; was needed. I added those.

I uncommented the console.log and changed to below to make it easily visible:
`console.log(" ****** debug ***",this._method,this._url);`

When I try to look at the this.url directly (open it in another tab, the return JSON is:
{"error":"unauthorized"}

I have tried (for example) these URLs and get the same error:
- https://screeps.com/api/user/world-status
- https://screeps.com/api/user/code?branch=$activeWorld   <-- Should this be value instead of variable??

I do not see the buttons or graph or anything showing up.

Let me know how to get started and I will be happy to help move this along.

**Comment by AlinaNova21** [comment]
most of the API urls require a valid token in the header, hence the unauthorized error. $activeWorld is automatically detected by the server.

**Comment by xyzzy529** [comment]
OK ... How do I get that token in the header?

What should I see on the screen or be able to test in the Console CLI to find out what it has done?

**Comment by AlinaNova21** [comment]
Looks like you are looking to mess with the API itself, which isn't what this project is for, however, theres some community docs at https://github.com/screepers/python-screeps/blob/master/docs/Endpoints.md
And a couple community libraries for simplifying connections and task over at https://github.com/screepers

**Comment by xyzzy529** [comment]
So what is this for?

And thanks for the references, I will read through those.

**Comment by AlinaNova21** [comment]
This just intercepts and console commands and replaces a few variables with values, ex: $i0 gets replaced by the ID of the selected object.

**Comment by xyzzy529** [comment]
could you give me an example of a sample console command and how to set the $i0 variable?
